environment:
  matrix:
  - julia_version: 1.0

platform:
  - x64 # 64-bit

install:
  - ps: iex ((new-object net.webclient).DownloadString("https://raw.githubusercontent.com/JuliaCI/Appveyor.jl/version-1/bin/install.ps1"))

build_script:
  - echo "%JL_BUILD_SCRIPT%"
  #- C:\julia\bin\julia ./build.jl
  - C:\julia\bin\julia "%JL_BUILD_SCRIPT%"

test_script:
  - echo "%JL_TEST_SCRIPT%"
  #- C:\julia\bin\julia ./runtests.jl
  - C:\julia\bin\julia "%JL_TEST_SCRIPT%"

